version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: prod
    ports:
      - "${PORT:-80}:80"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend